AllCops:
  Exclude:
    - config/**/*
    - vendor/**/*
    - public/**/*
    - spec/javascripts/**/*
    - spec/**/*
    - tasks/**/*
    - Guardfile

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false

Style/SpaceInsideRangeLiteral:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 200

Metrics/PerceivedComplexity:
  Max: 10

Lint/BlockAlignment:
  Enabled: false

inherit_from: .rubocop_todo.yml
